    
language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt -t skill_env
script:
  - python tests.py
deploy:
  provider: lambda
  function_name: "ucsb-sa-innovathon-alexa-bot"
  region: "us-west-2"
  role: "arn:aws:iam::035849207430:role/service-role/ucsb-sa-innovathon-alexa-bot-role-ae8k1d0z"
  runtime: "python2.7"
  handler_name: "handler"